appName = {{ item.SITE_NAME }}
languageName=enUS
appPath_enUS={{ item.SITE_SRC }}
domainName=heytate.com
domainPackageName={{ item.SITE_JAVA_PACKAGE }}
suffixSrcMainJava=/src/main/java
suffixSrcGenJava=/src/gen/java
relativePathsToWatch=src/main/java/{{ item.SITE_JAVA_PACKAGE | replace('.', '/') }}
jdbcHost="{{ POSTGRES_HOST_NAME }}"
jdbcPort=5432
jdbcDatabase="{{ SITE_DB_NAME_ENUS }}"
jdbcUsername={{ SITE_DB_USER_ENUS }}
jdbcPassword="{{ SITE_DB_PASSWORD_ENUS }}"
siteHostName={{ SITE_SITE_HOST_NAME_ENUS }}
siteBaseUrl={{ SITE_SITE_BASE_URL_ENUS }}
authRealm={{ AUTH_REALM }}
authResource={{ AUTH_RESOURCE }}
authSecret={{ AUTH_SECRET }}
authUrl={{ AUTH_URL }}
authSslRequired=all
sitePort={{ SITE_SITE_PORT_ENUS }}
solrUrl=http://{{ SOLR_HOST_NAME }}:{{ SOLR_PORT }}/solr/{{ SITE_SOLR_COLLECTION_ENUS }}
solrUrlComputate=http://{{ SOLR_HOST_NAME }}:{{ SOLR_PORT }}/solr/computate
apiContactEmail={{ EMAIL_FROM }}
siteZone={{ SITE_SITE_ZONE_ENUS }}
staticBaseUrl={{ SITE_STATIC_BASE_URL }}
staticPath={{ item.SITE_SRC }}-static
emailHost=
emailPort=
emailSsl=
emailAuth=
emailUsername=
emailPassword=
emailFrom=
emailAdmin=
sqlTables={{ SITE_CONFIG.sqlTables | default(true) }}
// Set the userKey of the user creating an object in the database. 
enableUserKey={{ SITE_CONFIG.enableUserKey | default(true) | lower }}
// Set the sessionId of the user session creating an object in the database. 
enableSessionId={{ SITE_CONFIG.enableSessionId | default(true) | lower }}
// Enable an object in the database to be deleted. 
enableDeleted={{ SITE_CONFIG.enableDeleted | default(true) | lower }}
// Enable an object in the database to be archived. 
enableArchived={{ SITE_CONFIG.enableArchived | default(true) | lower }}
