appName = {{ item.APP_NAME }}
languageName=enUS
appPath_enUS={{ item.APP_SRC }}
domainName=heytate.com
domainPackageName={{ item.APP_JAVA_PACKAGE }}
suffixSrcMainJava=/src/main/java
suffixSrcGenJava=/src/gen/java
relativePathsToWatch=src/main/java/{{ item.APP_JAVA_PACKAGE | replace('.', '/') }}
jdbcHost="{{ POSTGRES_HOST_NAME }}"
jdbcPort=5432
jdbcDatabase="{{ APP_DB_NAME_ENUS }}"
jdbcUsername={{ APP_DB_USER_ENUS }}
jdbcPassword="{{ APP_DB_PASSWORD_ENUS }}"
siteHostName={{ APP_SITE_HOST_NAME_ENUS }}
siteBaseUrl={{ APP_SITE_BASE_URL_ENUS }}
authRealm={{ AUTH_REALM }}
authResource={{ AUTH_RESOURCE }}
authSecret={{ AUTH_SECRET }}
authUrl={{ AUTH_URL }}
authSslRequired=all
sitePort={{ APP_SITE_PORT_ENUS }}
solrUrl=http://{{ SOLR_HOST_NAME }}:{{ SOLR_PORT }}/solr/{{ APP_SOLR_COLLECTION_ENUS }}
solrUrlComputate=http://{{ SOLR_HOST_NAME }}:{{ SOLR_PORT }}/solr/computate
apiContactEmail={{ EMAIL_FROM }}
siteZone={{ APP_SITE_ZONE_ENUS }}
staticBaseUrl={{ APP_STATIC_BASE_URL }}
staticPath={{ item.APP_SRC }}-static
emailHost=
emailPort=
emailSsl=
emailAuth=
emailUsername=
emailPassword=
emailFrom=
emailAdmin=
sqlTables={{ APP_CONFIG.sqlTables | default(true) }}
// Set the userKey of the user creating an object in the database. 
enableUserKey={{ APP_CONFIG.enableUserKey | default(true) | lower }}
// Set the sessionId of the user session creating an object in the database. 
enableSessionId={{ APP_CONFIG.enableSessionId | default(true) | lower }}
// Enable an object in the database to be deleted. 
enableDeleted={{ APP_CONFIG.enableDeleted | default(true) | lower }}
// Enable an object in the database to be archived. 
enableArchived={{ APP_CONFIG.enableArchived | default(true) | lower }}
